### PR TITLE
Add instructors to attendance.

### PR DESCRIPTION
**Pull request by s-moffatt**
Add instructors to attendance.
And clean up a few minor bugs.

### CODE REVIEW

**Comment by vicnl75** [comment]
@s-moffatt @mikesomlo @mmshaikh88 I've deployed the modified code to both dev and prod site.

Please test the add instructors attendance feature on the dev site:
1. Go to 'Classes' page. Pick a class and add an instructor email address as one of the 'owners' of the class. 
2. Go to 'Take Attendance' page. If there are any 'owners' assigned to the class, they should appear at end of the 
class list after the '--- Instructor ---' divider row. First/Last name will be displayed for any 'owners' email that is also defined as a teacher's email on the 'Teachers' page; otherwise the email address will be displayed. In the drop-down class list, any classes where the logged in user is one of the 'owners' will before the '---' divider line; all other classes will appear after the divider line. Try taking and editing attendance a few times one this page.
3. Go to 'View Attendance' page. If there are any 'owners' assigned to the class, they should appear at end of the 
class list after the '--- Instructor ---' divider row in the table footer. The table body (student list) is sortable on all columns; the sorting should not affect the table footer.
4. Go to 'Attendance Sheets' page. Generate attendance sheet PDF's including both classes with and without 'owners'. If there are any 'owners' assigned to the class, they should appear at end of the class list after the 'Instructor/Assistant' divider row. First/Last name will be displayed for any 'owners' email that is also defined as a teacher's email on the 'Teachers' page; otherwise the email address will be displayed. 

Please approve if everything good to go.

**Comment by mmshaikh88** [comment]
> @s-moffatt @mikesomlo @mmshaikh88 I've deployed the modified code to both dev and prod site.
> 
> Please test the add instructors attendance feature on the dev site:
> 
> 1. Go to 'Classes' page. Pick a class and add an instructor email address as one of the 'owners' of the class.
> 2. Go to 'Take Attendance' page. If there are any 'owners' assigned to the class, they should appear at end of the
>    class list after the '--- Instructor ---' divider row. First/Last name will be displayed for any 'owners' email that is also defined as a teacher's email on the 'Teachers' page; otherwise the email address will be displayed. In the drop-down class list, any classes where the logged in user is one of the 'owners' will before the '---' divider line; all other classes will appear after the divider line. Try taking and editing attendance a few times one this page.
> 3. Go to 'View Attendance' page. If there are any 'owners' assigned to the class, they should appear at end of the
>    class list after the '--- Instructor ---' divider row in the table footer. The table body (student list) is sortable on all columns; the sorting should not affect the table footer.
> 4. Go to 'Attendance Sheets' page. Generate attendance sheet PDF's including both classes with and without 'owners'. If there are any 'owners' assigned to the class, they should appear at end of the class list after the 'Instructor/Assistant' divider row. First/Last name will be displayed for any 'owners' email that is also defined as a teacher's email on the 'Teachers' page; otherwise the email address will be displayed.
> 
> Please approve if everything good to go.

@vicnl75 Can you share the URL where we need to test this?

**Comment by vicnl75** [comment]
@s-moffatt <https://github.com/s-moffatt> @mikesomlo
<https://github.com/mikesomlo> @mmshaikh88
<https://github.com/mmshaikh88> Please
test it at:
https://selectives3-dev.wn.r.appspot.com/

**Comment by s-moffatt** [comment]
I played around a bit and it looks good.

If an instructor has two entries in Teacher yaml (both with first and last name), then they will be listed twice in the attendance page and we won't be able to tell them apart. But we can work around it by keeping only one entry per person in the Teacher yaml. It seems workable, and maybe once we start using it something better will occur to us.

@vicnl75 Thanks for the fix!

**Review by vicnl75 — APPROVED** [review]
Tested by @s-moffatt

**Comment by vicnl75** [comment]
Thanks @s-moffatt for the testing. I had to re-open to merge the deployed code back to main.

**Pull request merged**
